parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - prettier
  - import
extends:
  - plugin:import/errors
  - prettier
rules:
  # prettier
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  # rules
  prefer-const: 2
  no-unused-vars: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
  # import
  import/newline-after-import: 2
  import/imports-first: 2
  import/no-dynamic-require: 2
  import/no-extraneous-dependencies: 2
  import/no-mutable-exports: 2
  import/no-commonjs: 2
